version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    image: frontend-service
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - OPENAI_API_KEY=($${OPENAI_API_KEY})
    env_file:
      - .env

  backend:
    build:
        context: .
        dockerfile: backend.Dockerfile
    image: backend-service
    ports:
      - "8000:8000"
