[runner]

magicEnabled = true


[theme]

# primaryColor="#F63366"
# backgroundColor="#FFFFFF"
# secondaryBackgroundColor="#F0F2F6"
# textColor="#262730"
# font="sans serif"


[server]
enableCORS = true
headless = true
port = 80
enableXsrfProtection = true
# sslCertFile = "/usr/src/app/certs/fullchain.pem"
# sslKeyFile = "/usr/src/app/certs/privkey.pem"

[browser]

serverAddress = "127.0.0.1"
gatherUsageStats = false
serverPort = 80
