[runner]

magicEnabled = true


[theme]

# primaryColor="#F63366"
# backgroundColor="#FFFFFF"
# secondaryBackgroundColor="#F0F2F6"
# textColor="#262730"
# font="sans serif"


[server]

# sslCertFile = 'fullchain.pem'
# sslKeyFile = 'privkey.pem'

folderWatchBlacklist = ['/src']
headless = true
runOnSave = false
port = 80
enableCORS = true


[browser]

serverAddress = "127.0.0.1"
gatherUsageStats = false
serverPort = 80
